import React from "react";
import Svg, { Path, Line, Rect } from "react-native-svg";

interface SportIconProps {
  size?: number;
  color?: string;
}

export function SportIcon({ size = 24, color = "#FFFFFF" }: SportIconProps) {
  return (
    <Svg width={size} height={size} viewBox="0 0 24 24" fill="none">
      <Line
        x1={12}
        y1={6}
        x2={12}
        y2={18}
        stroke={color}
        strokeWidth={1.8}
        strokeLinecap="round"
      />
      <Rect
        x={10.5}
        y={8}
        width={3}
        height={8}
        rx={1}
        stroke={color}
        strokeWidth={1.8}
        fill="none"
      />
      <Line
        x1={7}
        y1={9}
        x2={10.5}
        y2={9}
        stroke={color}
        strokeWidth={1.8}
        strokeLinecap="round"
      />
      <Line
        x1={7}
        y1={15}
        x2={10.5}
        y2={15}
        stroke={color}
        strokeWidth={1.8}
        strokeLinecap="round"
      />
      <Line
        x1={13.5}
        y1={9}
        x2={17}
        y2={9}
        stroke={color}
        strokeWidth={1.8}
        strokeLinecap="round"
      />
      <Line
        x1={13.5}
        y1={15}
        x2={17}
        y2={15}
        stroke={color}
        strokeWidth={1.8}
        strokeLinecap="round"
      />
      <Rect
        x={5}
        y={8}
        width={2}
        height={4}
        rx={0.8}
        stroke={color}
        strokeWidth={1.8}
        fill="none"
      />
      <Rect
        x={17}
        y={8}
        width={2}
        height={4}
        rx={0.8}
        stroke={color}
        strokeWidth={1.8}
        fill="none"
      />
      <Rect
        x={3}
        y={9}
        width={2}
        height={2}
        rx={0.5}
        stroke={color}
        strokeWidth={1.5}
        fill="none"
      />
      <Rect
        x={19}
        y={9}
        width={2}
        height={2}
        rx={0.5}
        stroke={color}
        strokeWidth={1.5}
        fill="none"
      />
      <Line
        x1={8}
        y1={18.5}
        x2={16}
        y2={18.5}
        stroke={color}
        strokeWidth={1.2}
        strokeLinecap="round"
        strokeDasharray="2 2"
      />
      <Line
        x1={9}
        y1={20.5}
        x2={15}
        y2={20.5}
        stroke={color}
        strokeWidth={1.2}
        strokeLinecap="round"
        strokeDasharray="2 2"
      />
    </Svg>
  );
}
